### ISSUE TITLE
NodeJS hot reload issue

### ISSUE THREAD

**Issue by tcastelly** [abiosoft/colima#261]
Hello,

I switched from Docker Desktop to Colima. I noticed an issue with "watcher" on bind volume. I created a repository: https://github.com/shenron/colima-hot-reload-issue

The container is not able to see when a file has been updated. But if I touch the file from the container it works. I guess it's linked to the volume.

---

I'm using the Macbook Pro M1 Max with:
```
colima version 0.3.4
git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae

runtime: docker
arch: aarch64
client: v20.10.14
server: v20.10.11
```

```
limactl version 0.9.2
```

**Comment by ggoodman** [comment]
The way colima binds host directories into the guest VM means that certain filesystem events are not observed / generated.

You can work around this by using `--legacy-watch` in `nodemon` that will fall back to polling instead of the [fsevents](https://npm.im/fsevents) integration.

**Comment by luiz290788** [comment]
I'm facing the same issue with `ts-node-dev`. Is this an issue that will eventually be solved by colima or we will never receive the same events when using colima?

**Comment by abiosoft** [comment]
>  Is this an issue that will eventually be solved by colima or we will never receive the same events when using colima?

I am working on a workaround taking a similar approach to https://github.com/abiosoft/colima/issues/261#issuecomment-1116466858 while leveraging inotify.  

I paused due to some issues with the Go library at the time, but I will revisit it.

**Comment by matthewdickinson** [comment]
> > Is this an issue that will eventually be solved by colima or we will never receive the same events when using colima?
> 
> I am working on a workaround taking a similar approach to [#261 (comment)](https://github.com/abiosoft/colima/issues/261#issuecomment-1116466858) while leveraging inotify.
> 
> I paused due to some issues with the Go library at the time, but I will revisit it.

It would be great to have this feature completed. Is there a work-in-progress branch that I could possibly help continue/test?

**Comment by djirik** [comment]
Hi, is there any progress on that? If you need some help, I may push our development team to help you. We need this so our frontend team could work using colima. Docker for mac is not an option for us)

**Comment by abiosoft** [comment]
@djirik support for **virtiofs** mounts is imminent and would be part of the next release. 

It has been merged into master upstream in Lima and currently being integrated and tested in Colima, the early results have been quite impressive.

Virtiofs is same tech used by Docker Desktop for the fast volume speeds.

**Comment by djirik** [comment]
@abiosoft thank you very much

**Comment by djirik** [comment]
@abiosoft Hi, do you have an idea when would it be available?

**Comment by abiosoft** [comment]
@djirik within the next week or two https://github.com/abiosoft/colima/issues/497#issuecomment-1345257182.

You can actually test it now if you can build Colima from source, it's on the `support-vz` branch.

**Comment by djirik** [comment]
@abiosoft hi again, I've succesfully switched to virtiofs on macOs 13. However `nodemon` still does not see updated files. 
```
colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/hacker/.colima/default/docker.sock
```

**Comment by abiosoft** [comment]
@djirik also, kindly confirm `lima --version` is `v0.1.4.0`?

**Comment by djirik** [comment]
@abiosoft 
yes, I have reset it. Unfortunately, I can not share source code, as it is under NDA.
```lima --version
limactl version 0.14.0
```
I can ask frontend team if they can make sample project without production code.

**Comment by djirik** [comment]
@abiosoft I have recreated colima again just to be sure, seems like it changed things a bit, now I'm having a lot of permission/access rights errors, I will fix it and return with more feedback.

**Comment by djirik** [comment]
@abiosoft File permissions are hell with virtiofs. I can't even launch node project with volume mounts. Can not figure out how to set user:group in compose file.

**Comment by abiosoft** [comment]
> @abiosoft File permissions are hell with virtiofs. I can't even launch node project with volume mounts. Can not figure out how to set user:group in compose file.

Do you have an idea of the userId in the container? You can check by running `id -u` in the container. 
What docker image are you using?

**Comment by djirik** [comment]
```yaml
version: '3.9'
services:
  nuxt:
    build:
      dockerfile: ../docker/nuxt/Dockerfile
      context: ./source
      target: node_base
    image: ${NUXT_IMAGE_NAME:-localhost/nuxt}:${NUXT_IMAGE_TAG:-latest}
    # user: $DEV_LOCAL_UID:$DEV_LOCAL_GID # here I've tried 501:20, 1000:1000, 501:1000, 0:0
    restart: 'no'
    environment:
      FORCE_COLOR: '1'
      NPM_TOKEN: $NPM_TOKEN
    entrypoint: sh
    command:
      - -xec
      - |-

        sleep 9999
        npm run npm-auth-repo --loglevel verbose

        npm install --loglevel verbose
        npm run dev --loglevel verbose
    volumes:
      - ./source:/app
      - ./volumes/nuxt/HOME:/home/node
```

```Dockerfile
FROM node:16.17.1-alpine AS node_base
WORKDIR /app

ENV HOST 0.0.0.0

EXPOSE 3000
```
Everytime I'm getting either 243 error from node, or permission denied for creating files in ```./volumes/nuxt/HOME```.
I've also tried `chmod +rwx` on `HOME` dir without effect.

**Comment by abiosoft** [comment]
As an unrecommended stopgap, the permission denied error should go away if you run `chmod -R 777 ./volumes/nuxt/HOME`.

Give me a moment, let me try to reproduce your error using the `node:16.17.1-alpine` image.

**Comment by abiosoft** [comment]
@djirik out of curiosity, why is `/home/node` getting mounted?

**Comment by djirik** [comment]
@abiosoft I've tried with 777, but it didn't have any effect. Yes, `/home/node` is mounted. `.npm` dir is created and after that it says permission denied)

**Comment by abiosoft** [comment]
@djirik I am unable to reproduce your permission issues. You can send me an email at the email on my GitHub profile and we can schedule a session to troubleshoot this.

As for the hot reload issue, I can confirm it is **not yet fixed** with virtiofs. Apparently, I was testing with a dotnet project and it works fine, and thereby assumed it catered for all other environments (including the node stack) as well.

**Comment by djirik** [comment]
@codingluke what is your node version?

**Comment by djirik** [comment]
@abiosoft I have sent you and email

**Comment by codingluke** [comment]
@djirik I use the latest 18.12.1. It is a docusaurus project.

- [Dockerfile ](https://github.com/codingluke/bbzbl-modul-431/blob/main/Dockerfile)
- [docker-compose.yaml](https://github.com/codingluke/bbzbl-modul-431/blob/main/docker-compose.yml)
- [package.json](https://github.com/codingluke/bbzbl-modul-431/blob/main/package.json)

![node version](https://user-images.githubusercontent.com/643436/208055376-505cf409-0833-4524-bbeb-0f7487d8a79a.png)

I just see, that I have different versions on host and container. Will adap

**Comment by djirik** [comment]
@codingluke I get it now, you are not mounting sources and NODE_HOME into container, this is why you don't have permission issues I guess.

**Comment by codingluke** [comment]
correct and I would recommend to only mount the part which is edited locally. I don't see the need to share node_modules and co.

**Comment by djirik** [comment]
@abiosoft I have skipped mounting /home/node, as it was found unnecessary, but hot reload is still not working :(. 

The working behavior is like this:
1. update file
2. `touch` file in `colima ssh` 
3. refresh is triggered.

Can we steal something from `Docker Desktop`, so it would work?

**Comment by abiosoft** [comment]
I assumed virtiofs will enable will enable hot reload out of the box. Since that has now turned out not to be the case, this would be resumed https://github.com/abiosoft/colima/issues/261#issuecomment-1219565057.

**Comment by codingluke** [comment]
I know it is not directly fitting this thread. However, I thought as a workaround for nodejs projects this could help 
- https://www.paolomainardi.com/posts/docker-performance-macos/#gui-editors--ide-users
- https://mutagen.io/documentation/synchronization

**Comment by rmachado-studocu** [comment]
Hey @abiosoft, is it still expectable a solution for the lack of fsevents ([based on your comment](https://github.com/abiosoft/colima/issues/261#issuecomment-1358919952))?

**Comment by abiosoft** [comment]
> Hey @abiosoft, is it still expectable a solution for the lack of fsevents ([based on your comment](https://github.com/abiosoft/colima/issues/261#issuecomment-1358919952))?

Yes !

**Comment by abiosoft** [comment]
Can someone try out the development version `brew install --HEAD colima` and try to experimental `--mount-inotify` flag?

```
colima start --mount-inotify
```

**Comment by rmachado-studocu** [comment]
> Can someone try out the development version `brew install --HEAD colima` and try the experimental `--mount-inotify` flag?
> 
> ```
> colima start --mount-inotify
> ```

I'll try that today! Thanks!

**Comment by henrik242** [comment]
I've got the same problem, which has [been discussed in a different 
 (closed) issue]:https://github.com/abiosoft/colima/issues/151#issuecomment-1475894687. I'll follow up here instead, since our issues are identical.  With the `--very-verbose` option to colima I can see in daemon.log that a file change is detected, but the file in questions isn't touched or hot reloaded.

**Comment by rmachado-studocu** [comment]
Hmmm first of all, just found out today that the only way to get that `daemon.log` is by triggering the `colima daemon start default --inotify` then follow it by `colima start ...` command

Next, yes I do see the same repeated inotify entries... In my case I'd guess that because the volumes are writable it is triggering a loop, where the host detects the write and sets again the modified datetime to the file written inside of the container, which triggers sort of a loop 🤔

**Comment by abiosoft** [comment]
> Hmmm first of all, just found out today that the only way to get that daemon.log is by triggering the colima daemon start default --inotify then follow it by colima start ... command

@rmachado-studocu you should never have to do that. It is an internal command and would be blocked from manually executation in future releases. Colima itself uses it command, that's why it's an hidden command and not visible in the cli docs.

You can always view the daemon logs at `~/.colima/default/daemon/daemon.log`. You can swap out `default` with the profile name if using separate profile. It can get very noisy in verbose mode.

```
tail -f ~/.colima/default/daemon/daemon.log
```

**Comment by abiosoft** [comment]
Thanks for your valuable feedbacks, I will iterate on the feature and update the thread accordingly.

**Comment by rmachado-studocu** [comment]
> You can always view the daemon logs at `~/.colima/default/daemon/daemon.log`.

Well, that file was never created... only when I had the `daemon` running it was created.

Thank you for your hard work! 😉

**Comment by abiosoft** [comment]
Can you try again with `brew install --head`? `colima version` should be git commit `e60e11652f72be1ab18b789ce024f761b5d37629`.

The infinite reload issue should be fixed now. 
The repo in the first comment now works from my tests https://github.com/shenron/colima-hot-reload-issue).

**Comment by rmachado-studocu** [comment]
Yeah I have the same ... in my case I have one of the containers running bundling and gulp tasks, which creates a bunch of `touch: <filepath>: Operation not permitted` lines ...

Also, again, without `colima daemon start --inotify` I cannot have the `daemon.log` created 🤷 I have to run that command before the colima start for some reason ...

Lastly, when changing the files, it still doesn't reload ... Btw, a bit more info on my case, I'm using docker-compose to start the containers... would that interfere? (yes the containers' mounts are already with `:rw` configurations)

**Comment by abiosoft** [comment]
@rmachado-studocu I think you are doing it wrong.

All you need is the following. Running the daemon directly will have unpredictable behaviour. Maybe reset the VM just to be sure.

```
colima start --mount-inotify 
```

**Comment by abiosoft** [comment]
> I re-created the vm. I still have the same issue. A simple touch from the host and the application restart for ever.

Something is off, did you use the `touch.sh` script?

**Comment by tcastelly** [comment]
> Something is off, did you use the `touch.sh` script?

I've just executed a:
> touch index.js

**Comment by abiosoft** [comment]
@tcastelly I'm also on m1 device.

You can see a video demonstration of the behaviour I am getting, it's working fine for me.
https://youtu.be/m3JbS9q7ukg

**Comment by tcastelly** [comment]
After installed Colima from the master branch do you think I have to delete a cache somewhere?

Or these commands are enough
 
```
colima delete
brew uninstall colima
brew install --HEAD colima
colima start --mount-inotify
```

**Comment by abiosoft** [comment]
@tcastelly are you using Qemu or VZ driver?

**Comment by rmachado-studocu** [comment]
@abiosoft so, in fact without doing the whole restart of the VM and stuff, I could see the inotify working 😄 the main problem is that the "inotify watcher" was flooded with `touch` requests and led to the update in the NEXT.js page to be delayed...

(The flood was mostly related to files being created/changed inside of the container. The container writes in a mounted volume with read+write access and that triggers events outside ... as said before)

But after the page updated, it led to the infinite loops of updates that @tcastelly is talking about ...

**Comment by tcastelly** [comment]
@abiosoft 

ah! Yes I use VZ that why I deleted the vm to don't have issue with this. But I guess it's not enough. 

> colima start --mount-inotify --vm-type=qemu

```
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/tcy/.lima/colima/serial.log")
```


But same behavior.  After a `touch index.js` the appplication restart for ever.

**Comment by abiosoft** [comment]
@tcastelly @rmachado-studocu you can try reinstalling development again and give it another try, the version is with git commit `f946b00e25f057a86e2b85aa509641de858409e6`.

**Comment by henrik242** [comment]
Still doesn't work for me
```
🐤 colima status
INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/henarons/.colima/default/docker.sock 
🐤 colima version
colima version HEAD-f946b00
git commit: f946b00e25f057a86e2b85aa509641de858409e6

runtime: docker
arch: aarch64
client: v23.0.1
server: v20.10.20
🐤 limactl --version
limactl version 0.15.0
```

**Comment by tcastelly** [comment]
I'm sorry, it not solved for me. The behavior is slightly different;

### with VZ
- `touch index.js` does not trigger all the time the watch
- when it triggers the application restart about 35 times
- same with vim, it does not trigger all the time the changes


### with qemu
- `touch index.js` trigger infinite changes

btw, @abiosoft, did you noticed when the application restart vim ask to reload the file? I guess It's because colima touch the file.

**Comment by henrik242** [comment]
Still doesn't work for me

```
$ colima version
colima version HEAD-cb9810a
git commit: cb9810a2ebe903ecbcdbe3e8c3983d12d7090530

runtime: docker
arch: aarch64
client: v23.0.1
server: v20.10.20
```

**Comment by abiosoft** [comment]
I will try testing on another device.

**Comment by tcastelly** [comment]
Right now I'm on this version"f52df980abb2adb2eb183599195913d8fd225008".  And it's better:
- `touch index.js` restart multiple times but no more infinite loop. I have between 0 and 3 restart.
- It's more difficult to trigger a change with vim. I'm wondering if it's because vim use cache system and replace the edited file https://github.com/fsnotify/fsnotify/issues/255#issuecomment-407575900

**Comment by tcastelly** [comment]
Yes of course the "hot-reload" experience it's the most important :). I'm talking about vim because I develop with it, not from the container/VM but as IDE on the host.

Anyway thx a lot for your work.

**Comment by abiosoft** [comment]
> I'm talking about vim because I develop with it, not from the container/VM but as IDE on the host.

oh, I thought you were referring to using it from the VM. Thanks for clarifying.

**Comment by henrik242** [comment]
Tried the latest, still no change.  Versions:
```
🐤 colima version
colima version HEAD-f52df98
git commit: f52df980abb2adb2eb183599195913d8fd225008
runtime: docker
arch: aarch64
client: v23.0.1
server: v20.10.20
🐤 colima status
INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/henarons/.colima/default/docker.sock 
```
I can still see `changed file modTime`, but no inotify event:
```
time="2023-03-21T07:33:57+01:00" level=trace msg="changed file modTime 2023-03-21 07:25:55.437541694 +0100 CET->2023-03-21 07:33:44.404863504 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
```

**Comment by abiosoft** [comment]
@henrik242 do you have any containers running?

It only monitors paths that are mounted in running containers.

**Comment by henrik242** [comment]
Yes, I have run `docker-compose up` containing a service with a volume mount as described in https://github.com/abiosoft/colima/issues/151#issuecomment-1475749566.

I might be misinterpreting your question, though. How would I expect to see a hot reload in a docker-run app without a running docker container?

**Comment by abiosoft** [comment]
@henrik242 can you mimic your project on a public repo or email it to me? I am not sure what is going wrong.

Or maybe email me to fix a time for us to get on a call. There may be specifics to your scenario that I am missing.

**Comment by rmachado-studocu** [comment]
Well, in my case, it is still looping...
I've done a change in one file which resulted in a repeating inotify:

![image](https://user-images.githubusercontent.com/89906313/226555286-b3570294-7a71-4324-99cc-0bae9e3c0eb3.png)

Now I have access to the `daemon.log` (thanks @abiosoft !) where I searched for `index.page.tsx` which basically showed me 108 finds at the time (and counting 😄 ):

![image](https://user-images.githubusercontent.com/89906313/226555570-d025d893-96df-4661-b3e1-b716ee4ecb5f.png)

**Comment by henrik242** [comment]
Could it be that the notifier is confused since I have overlapping mounts?  From `docker container inspect`:
```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/foo/src/baz/bar/web",
                "Destination": "/app",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/foo/src/baz/node_modules",
                "Destination": "/app/node_modules",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/Users/foo/src/baz/shared/frontend-resources/src",
                "Destination": "/app/shared",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

**Comment by rmachado-studocu** [comment]
Actually one thing I noticed in my log is that the line _found volumes_ shows certain volumes duplicated:

```
time="2023-03-21T10:15:40+01:00" level=trace msg="found volumes [/main-path/data/db /main-path/data/db /main-path/container-1 /main-path/container-1 /main-path/container-1 /main-path/container-2]" context=inotify
```

**Comment by henrik242** [comment]
> Could it be that the notifier is confused since I have overlapping mounts? From docker container inspect:

Yup, that was it! If I only keep the first mount and comment out the others, the notifier works. 🎉

**Comment by abiosoft** [comment]
Interesting, thanks for the feedback.

Let me try to reproduce and troubleshoot on my end.

**Comment by rmachado-studocu** [comment]
@henrik242 indeed it is related to the `volumes:` section. In my case I'm running a few containers, where the `/main-path/container-1` folder is shared across 3 different containers, hence the fact that appears 3x... The db folder is shared in 2 containers, so it appears 2x in the log...

@abiosoft perhaps [this line](https://github.com/abiosoft/colima/blob/main/daemon/process/inotify/volumes.go#L73) could contain a check if the path already exists in `vols`? 🤔

**Comment by abiosoft** [comment]
@rmachado-studocu @henrik242 can you check if you still get duplicate events with git commit `84b598c341ae63b2c490be5cc94396c093a1b5d1`?

**Comment by rmachado-studocu** [comment]
> @rmachado-studocu @henrik242 can you check if you still get duplicate events with git commit `84b598c341ae63b2c490be5cc94396c093a1b5d1`?

Checking it right away 😉

**Comment by henrik242** [comment]
@abiosoft I never had a duplicate events problem, so I'm checking if hot deploy works instead. It still doesn't (when I have overlapping volume mounts).

**Comment by abiosoft** [comment]
@henrik242 can you assist with testing with a scenario/project similar to yours? https://github.com/abiosoft/colima/issues/261#issuecomment-1477362511

**Comment by rmachado-studocu** [comment]
@abiosoft I've tested it (sorry it takes a bit, got in between meetings 😄 )

I do see an improvement... less inotify events are sent...

However I do see repeated events in the logs still:
[partial_daemon.log](https://github.com/abiosoft/colima/files/11029363/partial_daemon.log)

**Comment by henrik242** [comment]
> @henrik242 can you mimic your project on a public repo or email it to me? I am not sure what is going wrong.

Sorry, I haven't had time to do that yet.

**Comment by abiosoft** [comment]
@rmachado-studocu your analogy is not far off. However, there should now be  a max of 2 repeated events with the latest improvement I made.

Computing checksum is quite expensive and too slow to fit into this scenario. Now that I think of it, comparing file sizes can also be an option.

**Comment by vitorhenrique123** [comment]
Very cool @abiosoft! 
It looks like your new solution works fine on my mac M2. I'll switch to colima ^^ 
![image](https://user-images.githubusercontent.com/18515574/226740612-3145b5bb-d4ca-4891-935d-1783a3aaba30.png)

**Comment by henrik242** [comment]
Seems I managed to create a test project where inotify doesn't work at all.  I have a feeling I'm doing something wrong:
```
colima stop
colima delete
colima start --cpu 4 --memory 8 --mount-inotify --very-verbose
git clone https://github.com/henrik242/nextjs-colima-inotify-test
cd nextjs-colima-inotify-test/web
yarn build
docker build .
cd ..
docker-compose up
```
Now open http://localhost:4900/ and edit `foo` in web/src/components/Layout.tsx. The web page should change, but it doesn't.

But touching the file inside the container works:
```
docker exec -ti <containerId> touch /app/src/components/Layout.tsx
```
I'm on colima HEAD-eceb851

**Comment by abiosoft** [comment]
@henrik242 I've seen the issue. 
Hidden folders are currently ignored. i.e. folders prefixed with `.git`.

**Comment by abiosoft** [comment]
> Seems I managed to create [a test project](https://github.com/henrik242/nextjs-colima-inotify-test) where inotify doesn't work at all.

This actually works fine for me. 🤔

**Comment by henrik242** [comment]
> This actually works fine for me. 🤔 And evident in the container logs.

So weird. The file doesn't even show up in daemon.log here.  I'm on an M2 Mac, could that be relevant?

**Comment by abiosoft** [comment]
> > This actually works fine for me. 🤔 And evident in the container logs.
> 
> So weird. The file doesn't even show up in daemon.log here. I'm on an M2 Mac, could that be relevant?

@henrik242 can you share the output of `colima status`?

**Comment by henrik242** [comment]
```
🐤 colima status --very-verbose
TRAC[0000] cmd ["limactl" "info"]                       
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0000] cmd ["lima" "sudo" "cat" "/etc/colima/colima.json"] 
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
INFO[0000] colima is running using QEMU                 
TRAC[0000] cmd ["lima" "uname" "-m"]                    
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
INFO[0000] socket: unix:///Users/foo/.colima/default/docker.sock 
TRAC[0000] cmd ["lima" "sudo" "service" "k3s" "status"] 
````

**Comment by henrik242** [comment]
@abiosoft A colleague of mine (with an M1 Mac) tried my test repo with the same results as me: No hot redploy.

**Comment by rmachado-studocu** [comment]
I've also tried @henrik242 's example:

Worked in the first change then stopped ... and then you can see the inotify commands on the iterm

https://user-images.githubusercontent.com/89906313/226921507-ee38b554-3be7-44e7-8d66-5c2d083bffd0.mp4

[partial_daemon.log](https://github.com/abiosoft/colima/files/11040498/partial_daemon.log)

**Comment by abiosoft** [comment]
@rmachado-studocu can you check the container logs? Were the rebuilds?

**Comment by vitorhenrique123** [comment]
@abiosoft 
I have Monterey with M2 - Its working fine with your last commit
`colima start --verbose --very-verbose --mount-inotify --mount "/Users/:w"  --cpu 4 --memory 8 --mount-type virtiofs`

My colleague with Ventura M1 - Not working unless he uses --legacy-watch
`colima start --arch x86_64 --vm-type=vz --mount-type=virtiofs --vz-rosetta`

Another detail is that it seems to me the local file's checksum changes after the restart. Every time I save the file -> Vim detects a new version of the file that is more "up to date" than the local one.

**Comment by henrik242** [comment]
Now I've tried with `vz` too: 
```
🐤 colima start --arch aarch64 --vm-type=vz --vz-rosetta --very-verbose --mount-inotify
...
🐤 colima status
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/henarons/.colima/default/docker.sock 
```
Still no hot reload (unless I touch the file in the guest manually).

**Comment by abiosoft** [comment]
@henrik242 thanks for your feedback. I am trying to find an alternative approach that would be more consistent.

**Comment by deviantintegral** [comment]
For anyone looking for a "now" solution, I highly recommend looking at mutagen. Since it copies the files in to the container, an inotify event is generated and hot reloads work as expected: https://mutagen.io/documentation/introduction

**Comment by henrik242** [comment]
> For anyone looking for a "now" solution, I highly recommend looking at mutagen

Yeah, I've used similar workarounds. Both fswatch and watchman can watch a folder and sync files with a script as they change.

**Comment by abiosoft** [comment]
@henrik242 @rmachado-studocu can you kindly test again and give feedback, now on git commit `a9f4e9c251e2262d8e2fa0687443050757f8ceff`.

**Comment by henrik242** [comment]
@abiosoft This works so much better! The idea to use `chmod` instead of `touch` was nice too, because my host IDE doesn't complain about remote changes anymore. 

But in my work project some changes aren't getting through, as seen by the following log. Some changes to `Navigation.tsx` are discovered that aren't followed up with a `chmod` event:
```
time="2023-03-25T11:21:41+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:21:41+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:11.170017238 +0100 CET->2023-03-25 11:21:38.046349677 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
time="2023-03-25T11:21:41+01:00" level=info msg="refreshing mtime for /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx " context=inotify
time="2023-03-25T11:21:41+01:00" level=trace msg="cmd [\"lima\" \"/bin/chmod\" \"644\" \"/Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx\"]"
time="2023-03-25T11:21:46+01:00" level=trace msg="cmd [\"lima\" \"docker\" \"ps\" \"-q\"]"
time="2023-03-25T11:21:46+01:00" level=trace msg="found containers [13e504f5bfe0 8b920559fd04 1ed26c348cd1 c2662363c79c]" context=inotify
time="2023-03-25T11:21:46+01:00" level=trace msg="cmd int [\"lima\" \"docker\" \"inspect\" \"13e504f5bfe0\" \"8b920559fd04\" \"1ed26c348cd1\" \"c2662363c79c\"]"
time="2023-03-25T11:21:46+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:21:51+01:00" level=trace msg="cmd [\"lima\" \"docker\" \"ps\" \"-q\"]"
time="2023-03-25T11:21:51+01:00" level=trace msg="found containers [13e504f5bfe0 8b920559fd04 1ed26c348cd1 c2662363c79c]" context=inotify
time="2023-03-25T11:21:51+01:00" level=trace msg="cmd int [\"lima\" \"docker\" \"inspect\" \"13e504f5bfe0\" \"8b920559fd04\" \"1ed26c348cd1\" \"c2662363c79c\"]"
time="2023-03-25T11:21:51+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.199862378 +0100 CET->2023-03-25 11:21:42.47674752 +0100 CET: /Users/foo/src/baz/bar/web/build/next/build-manifest.json"
time="2023-03-25T11:21:56+01:00" level=info msg="refreshing mtime for /Users/foo/src/baz/bar/web/build/next/build-manifest.json " context=inotify
time="2023-03-25T11:21:56+01:00" level=trace msg="cmd [\"lima\" \"/bin/chmod\" \"644\" \"/Users/foo/src/baz/bar/web/build/next/build-manifest.json\"]"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.199287963 +0100 CET->2023-03-25 11:21:42.469971293 +0100 CET: /Users/foo/src/baz/bar/web/build/next/react-loadable-manifest.json"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.207567893 +0100 CET->2023-03-25 11:21:42.483883454 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/middleware-build-manifest.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.20660773 +0100 CET->2023-03-25 11:21:42.482665792 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/middleware-react-loadable-manifest.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.207585893 +0100 CET->2023-03-25 11:21:42.484233828 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/next-font-manifest.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.207643643 +0100 CET->2023-03-25 11:21:42.484497286 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/next-font-manifest.json"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:03.696816382 +0100 CET->2023-03-25 11:21:43.680181596 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/pages/_app.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:03.69989833 +0100 CET->2023-03-25 11:21:43.68278992 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/pages/index.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:03.683927051 +0100 CET->2023-03-25 11:21:43.679768597 +0100 CET: /Users/foo/src/baz/bar/web/build/next/server/pages-manifest.json"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.202016037 +0100 CET->2023-03-25 11:21:42.478228807 +0100 CET: /Users/foo/src/baz/bar/web/build/next/static/chunks/pages/_app.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.200360459 +0100 CET->2023-03-25 11:21:42.480148509 +0100 CET: /Users/foo/src/baz/bar/web/build/next/static/chunks/webpack.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.206803896 +0100 CET->2023-03-25 11:21:42.484026662 +0100 CET: /Users/foo/src/baz/bar/web/build/next/static/development/_buildManifest.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:02.206338814 +0100 CET->2023-03-25 11:21:42.482343876 +0100 CET: /Users/foo/src/baz/bar/web/build/next/static/development/_ssgManifest.js"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:20:03.765950108 +0100 CET->2023-03-25 11:21:43.743322133 +0100 CET: /Users/foo/src/baz/bar/web/build/next/trace"
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:21:38.046349677 +0100 CET->2023-03-25 11:21:47.264378037 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
time="2023-03-25T11:21:56+01:00" level=trace msg="cmd [\"lima\" \"docker\" \"ps\" \"-q\"]"
time="2023-03-25T11:21:56+01:00" level=trace msg="found containers [13e504f5bfe0 8b920559fd04 1ed26c348cd1 c2662363c79c]" context=inotify
time="2023-03-25T11:21:56+01:00" level=trace msg="cmd int [\"lima\" \"docker\" \"inspect\" \"13e504f5bfe0\" \"8b920559fd04\" \"1ed26c348cd1\" \"c2662363c79c\"]"
time="2023-03-25T11:21:56+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:22:01+01:00" level=trace msg="cmd [\"lima\" \"docker\" \"ps\" \"-q\"]"
time="2023-03-25T11:22:01+01:00" level=trace msg="found containers [13e504f5bfe0 8b920559fd04 1ed26c348cd1 c2662363c79c]" context=inotify
time="2023-03-25T11:22:01+01:00" level=trace msg="cmd int [\"lima\" \"docker\" \"inspect\" \"13e504f5bfe0\" \"8b920559fd04\" \"1ed26c348cd1\" \"c2662363c79c\"]"
time="2023-03-25T11:22:01+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:22:06+01:00" level=trace msg="cmd [\"lima\" \"docker\" \"ps\" \"-q\"]"
time="2023-03-25T11:22:06+01:00" level=trace msg="found containers [13e504f5bfe0 8b920559fd04 1ed26c348cd1 c2662363c79c]" context=inotify
time="2023-03-25T11:22:06+01:00" level=trace msg="cmd int [\"lima\" \"docker\" \"inspect\" \"13e504f5bfe0\" \"8b920559fd04\" \"1ed26c348cd1\" \"c2662363c79c\"]"
time="2023-03-25T11:22:06+01:00" level=trace msg="found volumes [/Users/foo/src/baz]" context=inotify
time="2023-03-25T11:22:10+01:00" level=trace msg="changed file mtime 2023-03-25 11:21:47.264378037 +0100 CET->2023-03-25 11:22:04.728632775 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
time="2023-03-25T11:22:10+01:00" level=info msg="refreshing mtime for /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx " context=inotify
time="2023-03-25T11:22:10+01:00" level=trace msg="cmd [\"lima\" \"/bin/chmod\" \"644\" \"/Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx\"]"
```

**Comment by abiosoft** [comment]
> @abiosoft This works so much better! 🎉 The idea to use chmod instead of touch was nice too, because my host IDE doesn't complain about remote changes anymore.

Good to hear :) Actually vim brought me here. Everything I tried triggered the vim warning for externally modified file except chmod.

Also, chmod only works at most once until the file is modified. i.e. subsequent chmod has no effect until the file is modified again, which suits our usecase. I suspect it is triggering some sort of flush behaviour that alerts the filesystem that the file has been modified. Running chmod on the host has no effect.

> But in my work project some changes aren't getting through, as seen by the following log. Some changes to Navigation.tsx are discovered, but aren't followed up with a chmod event.

Actually multiple events around same time are ignored, until around 500ms is passed. It is an attempt to mitigate responding to unecessary events that can happen during actions like refactor or renaming directories. It is not perfect but we can find the right balance.

I will be waiting for more positive feedback before embarking on the next phase of listening for filesystem events. 
Long polling is currently being used and will remain a fallback, but it can become resource intensive for very large projects.

**Comment by henrik242** [comment]
Yeah, I noticed the [500ms](https://github.com/abiosoft/colima/commit/a9f4e9c251e2262d8e2fa0687443050757f8ceff#diff-04b1d0f85b7b2e9228d09ecd56b6f09e5fc6c9ac41626553c1dfd34a761c4b80R37), but my changes are several seconds apart. This should have triggered a chmod, but it didn't:
```
time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:21:38.046349677 +0100 CET->2023-03-25 11:21:47.264378037 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
```

**Comment by abiosoft** [comment]
> Yeah, I noticed the [500ms](https://github.com/abiosoft/colima/blob/a9f4e9c251e2262d8e2fa0687443050757f8ceff/daemon/process/inotify/watch.go#L37), but my changes are several seconds apart. This should have triggered a chmod, but it didn't:
> 
> ```
> time="2023-03-25T11:21:56+01:00" level=trace msg="changed file mtime 2023-03-25 11:21:38.046349677 +0100 CET->2023-03-25 11:21:47.264378037 +0100 CET: /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx"
> ```

@henrik242 can you try again with git commit `083d2032e285c2ba2c47dec2f375c16e410797da` ?

**Comment by henrik242** [comment]
This looks worse. A change can take up to 15 seconds to propagate, and not all changes get through. I can send you a screen recording link, can I use the email in the git log?

**Comment by henrik242** [comment]
By the way, it looks like you are walking through all the files in the mounted file paths, is that correct? One of my mounts is a node_modules folder with *a lot* of files, so that might be slow.  Have you considered using something like https://github.com/fsnotify/fsnotify istead?

**Comment by abiosoft** [comment]
@henrik242 thanks for the feedback, I'd revert that asap.

> Have you considered using native [macOS FSEvents](https://developer.apple.com/documentation/coreservices/file_system_events) instead

Yeah, this is the plan. I want to get the hot-reload right before working on it.

> There seem to be partial (non-recursive) support for that in https://github.com/fsnotify/fsevents at least.

fsntofiy is a no-go for me, I ran into issues and it's lack of recursive support makes it even less attractive.

> This is also an alternative: https://github.com/rjeczalik/notify

This was outdated at the time (I initially took a jab a this) and could not get it to build, looks like there is recent update to the library. I might consider it again.

**Comment by abiosoft** [comment]
@henrik242 @rmachado-studocu kindly try out the latest update `02d01d9260d7c93d9c1861b1bea3b313a0e88b77`.

I think it's good to go now :)

**Comment by henrik242** [comment]
Tested now, but something seems wrong. It tries to notify things in my `~/Library`, such as:
```
time="2023-03-26T20:11:38+02:00" level=error msg="unable to stat inotify file '/Users/foo/Library/Caches/com.spotify.client/Browser/b5f70ca6cbc05b1d1fd9274food9ebfa071b1cc80/.com.spotify.client.AgKdOv': stat /Users/foo/Library/Caches/com.spotify.client/Browser/b5f70ca6cbc05bfoofd92749ed9ebfa071b1cc80/.com.spotify.client.AgKdOv: no such file or directory" context=inotify
time="2023-03-26T20:11:44+02:00" level=error msg="unable to stat inotify file '/Users/foo/Library/Caches/com.spotify.client/Browser/.com.spotify.client.v6F1h5': stat /Users/foo/Library/Caches/com.spotify.client/Browser/.com.spotify.client.v6F1h5: no such file or directory" context=inotify
time="2023-03-26T20:11:45+02:00" level=info msg="refreshing mtime for /Users/foo/Library/Caches/Google/Chrome/Profile 1/Cache/Cache_Data/bca585fpp0d08583_0 " context=inotify
time="2023-03-26T20:11:46+02:00" level=error msg="unable to stat inotify file '/Users/foo/Library/Caches/com.spotify.client/Browser/b5f70ca6cbc05b1d1fd92749ed9ebfa071b1cc80/.com.spotify.client.ylBbgh': stat /Users/foo/Library/Caches/com.spotify.client/Browser/b5f70ca6cbc05b1d1fd92749ed9ebfa071b1cc80/.com.spotify.client.ylBbgh: no such file or directory" context=inotify
time="2023-03-26T20:11:46+02:00" level=info msg="refreshing mtime for /Users/foo/Library/Logs/JetBrains/IntelliJIdea2022.3/indexing-diagnostic/storage-diagnostic-2023-03-23-10-38-25.675.json " context=inotify
time="2023-03-26T20:11:48+02:00" level=info msg="refreshing mtime for /Users/foo/Library/Caches/Google/Chrome/Profile 1/Cache/Cache_Data/3e3d3efoo9ed885fb_0 " context=inotify
time="2023-03-26T20:11:52+02:00" level=info msg="refreshing mtime for /Users/foo/Library/Caches/Firefox/Profiles/7dqvi1yz.dev-edition-default/cache2/entries/DD83DF733AF45F2E1C2FOO1F39528A9AE20E0CBE3 " context=inotify
time="2023-03-26T20:12:12+02:00" level=error msg="unable to stat inotify file '/Users/foo/src/baz/.idea/workspace.xml.tmp': stat /Users/foo/src/baz/.idea/workspace.xml.tmp: no such file or directory" context=inotify
```
Also, it doesn't notify on `Navigation.tsx` changes, only `Navigation.tsx~`:
```
time="2023-03-26T20:12:12+02:00" level=error msg="unable to stat inotify file '/Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx~': stat /Users/foo/src/baz/bar/web/src/components/navigation/Navigation.tsx~: no such file or directory" context=inotify
```

**Comment by abiosoft** [comment]
> Tested now, but something seems wrong. It tries to notify things in my ~/Library, such as

@henrik242 yeah it's now listing for FSEvents. Due to that, the overhead is minimal and can afford to watch entire VM volume (usually $HOME). I may revert back to only container mounted volumes to reduce the noise.

> Also, it doesn't notify on Navigation.tsx changes, only Navigation.tsx~:

I think I know what's happening here, some editors keep a copy of the file being edited (similar to vim) and the rate limit is preventing multiple events to go through. So I guess event for `Navigation.tsx~` is being sent before the actual file `Navigation.tsx`. I have pushed a fix to mitigate it and should be better now.

**Comment by henrik242** [comment]
`HEAD-9e533eb` has the same problem with `Navigation.tsx~`

**Comment by abiosoft** [comment]
> `HEAD-9e533eb` has the same problem with `Navigation.tsx~`

I have expanded the events being monitored to include `Create` and `Rename` events. 
I assumed that monitoring the `Write` events should suffice.

**Comment by henrik242** [comment]
Having the same issue with `HEAD-8e2a0e0` also :/

**Comment by abiosoft** [comment]
Thanks @henrik242 for the valuable feedbacks, https://github.com/abiosoft/colima/pull/668 has been merged.

Awaiting more feedbacks before working towards a release.

### Instructions

Install

```
brew install --HEAD colima
```

Usage

```
colima start --mount-inotify
```

**PS:** 
The plan is to have `--mount-inotify` removed (or at least default to `true`) for the release, provided the feedbacks are positive.

**Comment by rmachado-studocu** [comment]
Well, it's working 🙌 :

A bit of context, with regards to the logs below... I only changed a file `index.page.tsx` which triggered the below logs...
I do see _Operation not permitted_ errors, but those files are indeed created inside, so I wonder if those are expected 🤔 

In any case, it seems performant so far... 👍 

<details>
<summary>Logs upon change</summary>

```
time="2023-03-27T10:27:52+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/pages/benchmark/index.page.tsx " context=inotify
time="2023-03-27T10:27:52+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/pages/benchmark/index.page.tsx " context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json], output: \"chmod: /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/static/chunks/webpack.js " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/static/chunks/webpack.js], output: \"chmod: /root-path/folder-2/apps/app-name/.next/static/chunks/webpack.js: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/server/middleware-build-manifest.js " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/server/middleware-build-manifest.js], output: \"chmod: /root-path/folder-2/apps/app-name/.next/server/middleware-build-manifest.js: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/server/pages-manifest.json " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/server/pages-manifest.json], output: \"chmod: /root-path/folder-2/apps/app-name/.next/server/pages-manifest.json: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/server/pages/benchmark.js " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/server/pages/benchmark.js], output: \"chmod: /root-path/folder-2/apps/app-name/.next/server/pages/benchmark.js: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json], output: \"chmod: /root-path/folder-2/apps/app-name/.next/react-loadable-manifest.json: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:27:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/server/middleware-react-loadable-manifest.js " context=inotify
time="2023-03-27T10:27:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/server/middleware-react-loadable-manifest.js], output: \"chmod: /root-path/folder-2/apps/app-name/.next/server/middleware-react-loadable-manifest.js: Operation not permitted\", err: \"exit status 1\"" context=inotify
time="2023-03-27T10:28:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/cache/webpack/server-development/index.pack_ " context=inotify
time="2023-03-27T10:28:53+02:00" level=info msg="refreshing mtime for /root-path/folder-2/apps/app-name/.next/cache/webpack/server-development/index.pack_ " context=inotify
time="2023-03-27T10:28:53+02:00" level=error msg="error running [lima /bin/chmod 644 /root-path/folder-2/apps/app-name/.next/cache/webpack/server-development/index.pack_], output: \"chmod: /root-path/folder-2/apps/app-name/.next/cache/webpack/server-development/index.pack_: No such file or directory\", err: \"exit status 1\"" context=inotify
```

</details>

**Comment by abiosoft** [comment]
>  only changed a file index.page.tsx which triggered the below logs...
I do see _Operation not permitted_ errors, but those files are indeed created inside, so I wonder if those are expected 🤔

@rmachado-studocu more events are now expected due to the change from long-polling to watching filesystem events. 

As for the permission errors, a fix has been pushed that hopefully minimizes that. The log should be less noisy now unless you use the verbose flags.

Thanks :)

**Comment by michaeldiscala** [comment]
> Thanks @henrik242 for the valuable feedbacks, #668 has been merged.
> 
> Awaiting more feedbacks before working towards a release.
> 
> ### Instructions
> Install
> 
> ```
> brew install --HEAD colima
> ```
> 
> Usage
> 
> ```
> colima start --mount-inotify
> ```
> 
> **PS:** The plan is to have `--mount-inotify` removed (or at least default to `true`) for the release, provided the feedbacks are positive.



Thanks so much for the work on this feature! My team and I are so exited for it. I am testing locally with colima head and am not seeing events get into my containers. My steps so far have been:

```
brew install --HEAD colima
colima start --mount-inotify
```

I then created a new container with:
```
 docker run --rm -it --entrypoint bash --mount type=bind,source="$(pwd)",target=/app debian:bullseye-slim
```

And setup an INotify watcher with:

```
apt-get update
apt-get -y install inotify-tools
cd /app
inotifywait -m -e modify "."
```

When I then touch files on the host machine, I'm not seeing any events come through. When I repeat these same steps with docker desktop as my runtime, I am able to see the events come in. I'm running on Ventura 13.1.

Would it be expected for these events to be coming through? If so is there anything else I can try or any debugging info I can help surface?

Thanks again

**Comment by AndreasA** [comment]
This fix seems to work fine for vite dev server. would be nice to get an official release soon, so at least the switch is available to be used 😄

**Comment by abiosoft** [comment]
> And setup an INotify watcher with:
> 
> ```
> apt-get update
> apt-get -y install inotify-tools
> cd /app
> inotifywait -m -e modify "."
> ```

@michaeldiscala you should not need to do anything extra and no additional step is needed after `colima start --mount-inotify`. 

Can you kindly try again, then tail the daemon log and share the output?

```
tail -f ~/.colima/default/daemon/daemon.log
```

Thanks.

**Comment by michaeldiscala** [comment]
@abiosoft Sure!

The log that I see is as follows:
```
Received signal 15
time="2023-04-10T10:58:27-07:00" level=info msg="- - - - - - - - - - - - - - -"
time="2023-04-10T10:58:27-07:00" level=info msg="daemon started by colima"
time="2023-04-10T10:58:27-07:00" level=info msg="Run `/usr/bin/pkill -F /Users/mdiscala/.colima/default/daemon/daemon.pid` to kill the daemon"
time="2023-04-10T10:58:27-07:00" level=info msg="waiting for VM to start" context=inotify
time="2023-04-10T10:58:27-07:00" level=info msg="waiting 5 secs for VM" context=inotify
time="2023-04-10T10:58:27-07:00" level=info msg="Using search domains: [hsd1.ca.comcast.net]"
time="2023-04-10T10:58:27-07:00" level=info msg="waiting for clients..."
on_accept(): vmnet_return_t VMNET_INVALID_ARGUMENT
vmnet_write: Undefined error: 0
time="2023-04-10T10:58:33-07:00" level=info msg="waiting 5 secs for VM" context=inotify
time="2023-04-10T10:58:41-07:00" level=info msg="waiting 5 secs for VM" context=inotify
time="2023-04-10T10:58:47-07:00" level=info msg="waiting 5 secs for VM" context=inotify
time="2023-04-10T10:58:52-07:00" level=info msg="VM started" context=inotify
time="2023-04-10T10:58:57-07:00" level=error msg="error listing containers: error running [lima docker ps -q], output: \"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\", err: \"exit status 1\"" context=inotify
time="2023-04-10T10:59:48-07:00" level=info msg="syncing inotify event for /Users/mdiscala/Development/panorama/inotifytest/file1 " context=inotify
```

This error message stood out to me:
```
time="2023-04-10T10:58:57-07:00" level=error msg="error listing containers: error running [lima docker ps -q], output: \"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\", err: \"exit status 1\"" context=inotify
```

When I try to run `lima docker ps -q` I get:
```
FATA[0000] instance "default" does not exist, run `limactl start default` to create a new instance
```

and when I do `limactl list` I get:

```
❯ limactl list
NAME      STATUS     SSH                VMTYPE    ARCH      CPUS    MEMORY    DISK     DIR
colima    Running    127.0.0.1:52385    vz        x86_64    4       12GiB     60GiB    ~/.lima/colima
```

`colima list` gives:
```
❯ colima list
PROFILE    STATUS     ARCH      CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    x86_64    4       12GiB     60GiB    docker     192.168.107.2
```

I'm not sure if that error message is a red herring or not, but it seems to be happening because `lima docker ps -q` runs within the `default` instance, but mine is named `colima`.

Interestingly it does show that the daemon is noticing the events, they're just not making it into my container 🤔

**Comment by abiosoft** [comment]
> I'm not sure if that error message is a red herring or not, but it seems to be happening because lima docker ps -q runs within the default instance, but mine is named colima.

The error is expected initially until the startup is complete. Also, the context is preserved (via env vars) and it is not running in the default instance but simply showing the commands being used. 

What kind of project are you running?

**Comment by michaeldiscala** [comment]
> The error is expected initially until the startup is complete. Also, the context is preserved (via env vars) and it is not running in the default instance but simply showing the commands being used.

Gotcha! Thanks for explaining

> What kind of project are you running?

For this test, I'm just running a one off container started with `docker run --rm -it --entrypoint bash --mount type=bind,source="$(pwd)",target=/app debian:bullseye-slim` and then using the inotify tools to check for messages. Is that what you mean by project?

I also checked and confirmed that I'm seeing this for both qemu + sshfs and vz + virtiofs (I was wondering if using virtiofs might be contributing)

**Comment by abiosoft** [comment]
@michaeldiscala this solution is not actually propagating inotify events from the host, it's a workaround to simulate the behaviour. Probably why the inotify tools are not picking it up.

In fact, the goal is to provide the "hot reload" developer experience, rather than inotify events.

**Comment by michaeldiscala** [comment]
Ah gotcha @abiosoft, thanks for explaining! Looking through the patch itself some more, I realized that you're passing the event through by running a `chmod` on the file.

When I update my test to listen to *all* inotify events (instead of just modification events like in my original run):

```
apt-get update
apt-get -y install inotify-tools
cd /app
inotifywait -m -e modify "."
```

I see events coming through as expected:
```
Setting up watches.
Watches established.
./ ATTRIB file.rb
./ ATTRIB file.rb
```

It's just that all of the modifications come in as `ATTRIB` events instead of `MODIFY` events. I think that should work with our hot-reloading systems and so will flag for our team to investigate. Thanks so much for all the development effor there and for helping me understand what I was seeing.

**Comment by rffensick** [comment]
hello guys, can someone help me, i got some error. colima 0.5.4 already installed

![image](https://user-images.githubusercontent.com/16798940/233578937-65feff47-cdb5-49e3-b99f-870f00725d0e.png)

**Comment by matleh** [comment]
@rffensick you need the HEAD version of colima (`brew install --HEAD colima`).

**Comment by rffensick** [comment]
@matleh thank you!

**Comment by rffensick** [comment]
after updating and trying to start all of the containers that I have in my project, I have almost all of the containers exit with error 139

![image](https://user-images.githubusercontent.com/16798940/233581437-620db29e-73c2-4d0f-a1e3-42c153ff3aa9.png)
![image](https://user-images.githubusercontent.com/16798940/233581475-a37bf062-1574-407d-95c1-ee950cb7ddde.png)

**Comment by rffensick** [comment]
start colima with command: `colima start --profile amd64 --cpu 4 --memory 8 --mount-inotify`

**Comment by jlholm** [comment]
@abiosoft #668 resolved hot reloading for me, thank you for your hard work!

**Comment by abiosoft** [comment]
With the amount of positive feedbacks received so far, a release would be made soon.

Thanks.

**Comment by niklaswolf** [comment]
Works on my machine, too. 
Great work, looking forward to have this in the new release :)

**Comment by jklmnop** [comment]
I am using the HEAD of Colima and it still doesn't seem to be working for me. I can edit files in the container and my watchers will detect the changes, but not if I edit files in my IDE. Any assistance is appreciated!

<img width="229" alt="image" src="https://github.com/abiosoft/colima/assets/180323/e1babe12-f509-48f0-837f-bdfee1295f78">

Here is my config
```yaml
# Number of CPUs to be allocated to the virtual machine.
# Default: 2
cpu: 4

# Size of the disk in GiB to be allocated to the virtual machine.
# NOTE: changing this has no effect after the virtual machine has been created.
# Default: 60
disk: 100

# Size of the memory in GiB to be allocated to the virtual machine.
# Default: 2
memory: 6

# Architecture of the virtual machine (x86_64, aarch64, host).
# Default: host
arch: host

# Container runtime to be used (docker, containerd).
# Default: docker
runtime: docker

# Kubernetes configuration for the virtual machine.
kubernetes:
  # Enable kubernetes.
  # Default: false
  enabled: false

  # Kubernetes version to use.
  # This needs to exactly match a k3s version https://github.com/k3s-io/k3s/releases
  # Default: latest stable release
  version: v1.25.4+k3s1

  # Disable k3s features [coredns servicelb traefik local-storage metrics-server].
  # All features are enabled unless disabled.
  #
  # EXAMPLE - disable traefik and metrics-server
  # disable: [traefik, metrics-server]
  #
  # Default: [traefik]
  disable:
    - traefik

# Auto-activate on the Host for client access.
# Setting to true does the following on startup
#  - sets as active Docker context (for Docker runtime).
#  - sets as active Kubernetes context (if Kubernetes is enabled).
# Default: true
autoActivate: true

# Network configurations for the virtual machine.
network:
  # Assign reachable IP address to the virtual machine.
  # NOTE: this is currently macOS only and ignored on Linux.
  # Default: false
  address: false

  # Custom DNS resolvers for the virtual machine.
  #
  # EXAMPLE
  # dns: [8.8.8.8, 1.1.1.1]
  #
  # Default: []
  dns:
    - 8.8.8.8

  # DNS hostnames to resolve to custom targets using the internal resolver.
  # This setting has no effect if a custom DNS resolver list is supplied above.
  # It does not configure the /etc/hosts files of any machine or container.
  # The value can be an IP address or another host.
  #
  # EXAMPLE
  # dnsHosts:
  #   example.com: 1.2.3.4
  dnsHosts: {}

  # Network driver to use (slirp, gvproxy), (requires vmType `qemu`)
  #   - slirp is the default user mode networking provided by Qemu
  #   - gvproxy is an alternative to VPNKit based on gVisor https://github.com/containers/gvisor-tap-vsock
  # Default: gvproxy
  driver: gvproxy

# ===================================================================== #
# ADVANCED CONFIGURATION
# ===================================================================== #

# Forward the host's SSH agent to the virtual machine.
# Default: false
forwardAgent: false

# Docker daemon configuration that maps directly to daemon.json.
# https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file.
# NOTE: some settings may affect Colima's ability to start docker. e.g. `hosts`.
#
# EXAMPLE - disable buildkit
# docker:
#   features:
#     buildkit: false
#
# EXAMPLE - add insecure registries
# docker:
#   insecure-registries:
#     - myregistry.com:5000
#     - host.docker.internal:5000
#
# Colima default behaviour: buildkit enabled
# Default: {}
docker: {}

# Virtual Machine type (qemu, vz)
# NOTE: this is macOS 13 only. For Linux and macOS <13.0, qemu is always used.
#
# vz is macOS virtualization framework and requires macOS 13
#
# Default: qemu
vmType: vz

# Utilise rosetta for amd64 emulation (requires m1 mac and vmType `vz`)
# Default: false
rosetta: true

# Volume mount driver for the virtual machine (virtiofs, 9p, sshfs).
#
# virtiofs is limited to macOS and vmType `vz`. It is the fastest of the options.
#
# 9p is the recommended and the most stable option for vmType `qemu`.
#
# sshfs is faster than 9p but the least reliable of the options (when there are lots
# of concurrent reads or writes).
#
# Default: virtiofs (for vz), sshfs (for qemu)
mountType: virtiofs

# Propagate inotify file events to the VM.
# NOTE: this is experimental.
mountInotify: true

# The CPU type for the virtual machine (requires vmType `qemu`).
# Options available for host emulation can be checked with: `qemu-system-$(arch) -cpu help`.
# Instructions are also supported by appending to the cpu type e.g. "qemu64,+ssse3".
# Default: host
cpuType: ""

# For a more general purpose virtual machine, Ubuntu container is optionally provided
# as a layer on the virtual machine.
# The underlying virtual machine is still accessible via `colima ssh --layer=false` or running `colima` in
# the Ubuntu session.
#
# Default: false
layer: false

# Custom provision scripts for the virtual machine.
# Provisioning scripts are executed on startup and therefore needs to be idempotent.
#
# EXAMPLE - script exected as root
# provision:
#   - mode: system
#     script: apk add htop vim
#
# EXAMPLE - script exected as user
# provision:
#   - mode: user
#     script: |
#       [ -f ~/.provision ] && exit 0;
#       echo provisioning as $USER...
#       touch ~/.provision
#
# Default: []
provision: []

# Modify ~/.ssh/config automatically to include a SSH config for the virtual machine.
# SSH config will still be generated in ~/.colima/ssh_config regardless.
# Default: true
sshConfig: true

# Configure volume mounts for the virtual machine.
# Colima mounts user's home directory by default to provide a familiar
# user experience.
#
# EXAMPLE
# mounts:
#   - location: ~/secrets
#     writable: false
#   - location: ~/projects
#     writable: true
#
# Colima default behaviour: $HOME and /tmp/colima are mounted as writable.
# Default: []
mounts: []

# Environment variables for the virtual machine.
#
# EXAMPLE
# env:
#   KEY: value
#   ANOTHER_KEY: another value
#
# Default: {}
env: {}
```

**Comment by Congee** [comment]
Unfortunately, I had a worse experience than [michaeldiscala](https://github.com/michaeldiscala) No inotify events show up at all in daemon.log or by manually running inotifywait in the vm.

I am on macOS 13.4.1 and other info you may need
colima version 0.5.5
arch: aarch64
runtime: containerd
mountType: virtiofs
kubernetes: enabled

**Comment by ploxiln** [comment]
I'm testing colima 0.5.5 with this experimental `--mount-inotify` option, and it not quite working for my use-case because it seems that all changes appear to be mode / attribute changes. BTW I'm testing with vm-type=vz mount-type=virtiofs

```
/ # inotifywait -m -r /mnt/app
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/mnt/app/example_app_drf/ ATTRIB urls.py
/mnt/app/example_app_drf/ ATTRIB new.py
/mnt/app/ ATTRIB supernew.txt
/mnt/app/ ATTRIB wsgi.py
^C
```

My setup (with which I currently use Docker Desktop ...) happens to use [reflex](https://github.com/cespare/reflex) and it (reasonably?) which seems to ignore these attribute/mode changes, waiting for some file contents change:

```
$ reflex --verbose -- sh -c "echo RESTART"
Globals set at commandline
| --verbose (-v) 'true' (default: 'false')
+---------
Reflex from [commandline]
| ID: 0
| Inverted regex match: "(^|/)\\.git/"
...
| (Implicitly matching all non-excluded files)
| Substitution symbol {}
| Command: [sh -c echo RESTART]
+---------

[info] fsnotify event: "./wsgi.py": CHMOD
[info] fsnotify event: "./wsgi.py": CHMOD
[info] fsnotify event: "./verynewfile.py": CHMOD
^CInterrupted (interrupt). Cleaning up children...
```

... I wonder if this is part of the design of how the fs events simulated/triggered inside the VM? Is it hard to change?

(I also notice that "rm" (unlink) and "touch" (ctime) are not propagated, but that is probably OK for my use-case ...)

---------

Here's the Docker Desktop inotify event emulation to compare:

```
/ # inotifywait -m -r /mnt/app
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
/mnt/app/ CREATE verynewfile2.py
/mnt/app/ MODIFY verynewfile2.py
/mnt/app/ ATTRIB wsgi.py
/mnt/app/ MODIFY wsgi.py
/mnt/app/example_app_drf/healthcheck/ CREATE views.py
/mnt/app/example_app_drf/healthcheck/ MODIFY views.py
/mnt/app/example_app_drf/healthcheck/ CREATE views.py
/mnt/app/example_app_drf/healthcheck/ ATTRIB views.py
/mnt/app/example_app_drf/healthcheck/ MODIFY views.py
/mnt/app/ MODIFY wsgi.py
```

and for _reflex_ (slightly modified command but doesn't matter):

```
$ reflex --verbose -- sh -c 'echo RESTART'
...

[info] fsnotify event: "./wsgi.py": WRITE
[00] RESTART
[info] fsnotify event: "./verynewfile4.py": CREATE
[info] fsnotify event: "./verynewfile4.py": WRITE
[00] RESTART
[info] fsnotify event: "example_app_drf/healthcheck/views.py": REMOVE
[info] fsnotify event: "example_app_drf/healthcheck/views.py": WRITE
[info] fsnotify event: "example_app_drf/healthcheck/views.py": CREATE
[info] fsnotify event: "example_app_drf/healthcheck/views.py": CHMOD
[info] fsnotify event: "example_app_drf/healthcheck/views.py": WRITE
[00] RESTART
```

Anyway, much thanks for what you've made with colima thus far, and I hope this report may help either improve or clarify the inotify feature in the future 😁

**Comment by F9Uf** [comment]
Hi, I have the same issue with @ploxiln . It doesn't work when I use reflex in docker-compose command.

**Comment by chrismith-equinix** [comment]
Hi @abiosoft - Is `--mount-inotify` expected to work with Kubernetes enabled?

**Comment by abiosoft** [comment]
> Hi @abiosoft - Is `--mount-inotify` expected to work with Kubernetes enabled?

@chrismith-equinix docker containers with mounted volumes are monitored, so it should work if the Kubernetes pod has a mounted volume.

**Comment by abiosoft** [comment]
> Great thanks @abiosoft ... We are using containerd runtime instead of docker. It should work with containerd images as well?

Having looked at the implementation, I can see that only the `default` namespace is being monitored for containerd. That needs to be fixed to monitor all namepaces include `k8s.io`.

**Comment by abiosoft** [comment]
@chrismith-equinix can you kindly create another issue for that?

Thanks.

**Comment by abiosoft** [comment]
I would be closing this issue as I think it has outlived it's purpose.
Hot reload now works for most users and inotify is now enabled by default.

Anyone is free to create new issue(s) for the remaining use cases that are yet to be covered.

Thanks to everyone that has contributed so far.

**Comment by chrismith-equinix** [comment]
@abiosoft - My workloads are not running in the `default` namespace currently, and I can see that it doesn't seem to be working. I will test it in the `default` namespace first, then create an issue for this.

Thanks for looking into this, and the timely response. It is appreciated
